### ISSUE TITLE
ARKV6X 3D PDF.PDF is blank.

### ISSUE THREAD

**Issue by ocularmagic** [ARK-Electronics/ARKV6X_Flight_Controller#1]
Hello, I downloaded and tried to open [ARKV6X 3D PDF.PDF](https://github.com/ARK-Electronics/ARKV6X_Flight_Controller/blob/main/ARKV6X%203D%20PDF.PDF) and it just has one blank page.

**Comment by AlexKlimaj** [comment]
You need to download the file and open it in adobe reader. Then you need to trust the document and allow the content. Let me know if that works and we can close the issue.

**Comment by ocularmagic** [comment]
Yes, that worked. Thanks!
